### ISSUE TITLE
Populate ownerReferences in the children of fiaas TPR/CRD's

### ISSUE THREAD

**Issue by birgirst** [fiaas/fiaas-deploy-daemon#10]
It would be great if fiaas populated the ownerReferences of resources created by fiaas. This would enable us to navigate to the fiaas definition from an ingress object for example.

https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/

**Comment by mortenlj** [comment]
Related to #78

**Comment by mortenlj** [comment]
@gregjones : Was this issue fixed in #95, or is there still something left?

**Comment by gregjones** [comment]
I think it can be closed.
