### ISSUE TITLE
Option to disable service links environment variables

### ISSUE THREAD

**Issue by xavileon** [fiaas/fiaas-deploy-daemon#104]
k8s injects a bunch of service links variables to be able to reach other services within a namespace via env vars. This feature is deprecated since a lot time ago. However, those environment variables are being injected anyway which makes some services to fail (e.g specific example being nodejs apps).

Disabling this environment variables injection is already possible in k8s 1.13 via the `enableServiceLinks` flag in the [PodSpec](https://v1-15.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#podspec-v1-core).

It would be helpful to get this flag configurable (possibly default to false? given it shouldn't be used as it's a deprecated feature).

**Comment by tg90nor** [comment]
I'm ok with implementing this as a configurable flag. Just keep in mind fiaas-deploy-daemon is in use in clusters with kubernetes 1.12, so it needs to work for those. I also thing it should default to true, since that is what kubernetes is doing.

**Comment by xavileon** [comment]
great! yeah, I think FIAAS is currently supporting k8s versions starting from 1.9 according to [tests](https://github.com/fiaas/fiaas-deploy-daemon/blob/master/tests/fiaas_deploy_daemon/conftest.py#L192), so the implementation should handle different k8s versions indeed.

**Comment by mortenlj** [comment]
There is probably some value in checking if we still need to support the oldest versions.

**Comment by oyvindio** [comment]
It is generally not a good idea to use the service host/port environment variables, so I think it makes a lot of sense to make it possible to configure `enableServiceLinks` at the fiaas-deploy-daemon instance level.

**Comment by blockjesper** [comment]
Done.
