### ISSUE TITLE
e2e tests fail because kind images for 1.12 and 1.14 have expired certificates

### ISSUE THREAD

**Issue by oyvindio** [fiaas/fiaas-deploy-daemon#115]
It looks like the CI build for #105 fails because the kind clusters used for e2e tests with Kubernetes version 1.12 and 1.14 fail to start. I looked into it and it looks like it might be the same issue with expired certificates which was fixed for Kubernetes 1.9 in #45 . Looks like we might need a similar fix for these Kubernetes versions too.

I found this in the kubelet logs from the kind docker container:
```
E0922 09:27:13.978134     405 bootstrap.go:264] Part of the existing bootstrap client certificate is expired: 2020-09-10 23:17:42 +0000 UTC
```

**Comment by mortenlj** [comment]
So essentially, this is a problem that stems from staying on too old versions of kubernetes?

**Comment by oyvindio** [comment]
> So essentially, this is a problem that stems from staying on too old versions of kubernetes?

Well, at least that increases the probability of running into this issue since it seems like the certificates used in the kind images expire after some time. If we can remove some of the older versions from the e2e tests, that might help avoid similar issues later.

**Comment by gregjones** [comment]
We currently have clusters with 1.9, 1.14 and 1.15 in use

**Comment by oyvindio** [comment]
I've built a new image for Kubernetes 1.12 as `fiaas/kind:v1.12.10` from bsycorp/kind@5b67b70 following the same procedure as described in https://github.com/fiaas/fiaas-deploy-daemon/pull/45
