### ISSUE TITLE
Propagation of config flags as environment variables can lead to config changes not taking effect on redeploy

### ISSUE THREAD

**Issue by oyvindio** [fiaas/fiaas-deploy-daemon#12]
When fiaas-deploy-daemon deploys itself, it sets some environment variables based on the internal state of its config object (see below). Since the config object is based on data from environment variables and the `cluster_config.yaml` file being merged (in that order), this can lead to a configuration change in the cluster_config.yaml file not being picked up since a value is already set in the corresponding environment variable.

https://github.com/fiaas/fiaas-deploy-daemon/blob/4d4bf405dd0ac729292f442513f9589a9b0516fe/fiaas_deploy_daemon/deployer/kubernetes/deployment/deployer.py#L223-L236

The typical way this occurs is when bootstrapping fiaas-deploy-daemon via Skipper. When this is done, the `fiaas-deploy-daemon` configmap, which usually provides the `cluster_config.yaml` file is not mounted in the Pod. This means that the default values for flags like `FIAAS_ENVIRONMENT` and `LOG_FORMAT` are used. To change these later, just changing the configmap is not enough; to make the config change actually be applied you have to change the configmap, then remove the corresponding environment variables from the fiaas-deploy-daemon deployment resource, which will trigger a redeploy that then applies the changes. 

This behavior might be improved by not propagating the state from the internal config object at all when fiaas-deploy-daemon is deploying itself

**Comment by mortenlj** [comment]
It might be worth looking into if we really need this behaviour at all. If we say fdd should always read its config from file and ignore the environment, the environment variables will only be used by normal apps in the cluster.
We already have a different mechanism for setting global env-variables, where the cluster config explicitly defines the values. .

**Comment by srvaroa** [comment]
+1, using always config files seems like the simplest choice to remove ambiguity.

**Comment by mortenlj** [comment]
We currently load config from environment variables, config file or options on the command line. Both command line and environment variables are quite limited (string values only), while the config file is YAML and could potentially support more complex values.

We already have a few values that would be easier to express using complex values, and we are discussing others. We need to consider if we need to be able to configure all values using environment values and/or command line options, or if we should do all configuration using the config file?

**Comment by oyvindio** [comment]
I think it makes sense to remove the ability to configure fiaas-deploy-daemon via environment variables, as already suggested in this ticket. It is confusing to troubleshoot this behavior when fiaas-deploy-daemon deploys itself, and configuring via environment variables isn't as expressive as using the configuration file/ConfigMap. It would still be possible to use command line args, so using a configuration file would still not be required.

I have a hard time coming up with a good  way to implement this in a backwards compatible manner, since that would basically require a configuration flag to disable reading environment variables. That becomes a bit of a catch 22 situation since that configuration flag would have to be read before reading the (other) configuration flags. One thing that might work is to introduce an environment variable to *enable* the current behavior of using environment variables to set configuration flags. That would make it easier for anyone already using environment variables for configuration to continue to do that, but it would still be a breaking change. It is of course technically possible to have this environment variable *disable* the current behavior, but that would require everyone using the other configuration mechanisms to set an environment variable, which is inconvenient when using configuration file or command line flags as the primary configuration method.
Anyone have any thoughts on how this should be done?

**Comment by mortenlj** [comment]
I think the backwards compatibility is pretty much present already?

You can already change your setup to use a config file, so transitioning to not using environment variables is something you can do today. Assuming we don't want to continue supporting environment variables forever, at some point we need to stop reading them. Adding a flag to enable reading them again only increases the complexity with benefits that can be more easily obtained by simply waiting longer between steps.

My suggested approach:

  1. Start logging a prominent warning if we detect that some configuration is read from environment variables, and communicate clearly that that way of configuring things is going away. 
  2. Announce anywhere it makes sense that we are removing support for configuring fiaas-deploy-daemon via environment variables, and that operators should switch to configmaps
  3. Wait a suitable amount of time
  4. 1. Repeat announcement above, but this time mentioning that this is happening now
      2. Remove the support for environment variables
