### ISSUE TITLE
CI builds for PRs from forks doesn't run e2e tests

### ISSUE THREAD

**Issue by oyvindio** [fiaas/fiaas-deploy-daemon#131]
CI builds for PRs from forks doesn't run e2e tests because secrets aren't exposed in builds for forked PRs, and they are necessary to `docker login`, which happens before the e2e test run as it is now.
It would be good to change the CI config to make it possible to have full CI builds including e2e tests on forked PRs too. It is probably not a good idea to expose secrets for those builds, but rather change how the build is done for PRs. I don't think docker login shouldn't be strictly necessary to run the e2e tests as it shouldn't need to push images, only build it.

**Comment by oyvindio** [comment]
It might be worth setting up manual approval (https://docs.semaphoreci.com/essentials/project-workflow-trigger-options/#approve-forked-pull-requests) of CI builds for forked PRs since e2e tests take some time to run.

**Comment by mortenlj** [comment]
I've changed some settings now, which I believe makes it possible for a selection of users to use the `/sem-approve` comment to trigger building forked PRs, exposing the docker secret to those builds. My understanding is that only builds triggered by such a comment (or not from a fork) has access to the docker secret, but I haven't been able to verify this.

**Comment by oyvindio** [comment]
I'm closing this since using the `/sem-approve` seems to work now (see #128)
