### ISSUE TITLE
e2e test suite Kubernetes version cleanup

### ISSUE THREAD

**Issue by oyvindio** [fiaas/fiaas-deploy-daemon#148]
It has been a while since updated the e2e test suite Kubernetes versions list was updated last, and some of the Kubernetes versions used there are getting somewhat dated, so I think it would be a good idea to see if it is possible to remove some of the older Kubernetes versions used in the test suite. Run time for e2e tests is getting longer, and more tests mean more complexity and more flakiness of the test suite as a whole. There is also some maintenance upkeep with keeping the older kind images working since there are some certificates for cluster-internal use which tend to expire one year after image build time (see #45, #116). 
From our perspective, I think it would be okay to keep only 1.16 and 1.18 (added in #147) out of the currently tested versions. Are there any Kubernetes versions we can remove from the test suite now? / which Kubernetes versions would you prefer to keep testing against ?

**Comment by oyvindio** [comment]
The Kubernetes versions the test suite currently covers can be found here: https://github.com/fiaas/fiaas-deploy-daemon/blob/master/tests/fiaas_deploy_daemon/conftest.py#L192-L196

**Comment by gregjones** [comment]
We still have a 1.9 cluster, and then 1.15, which I don't think I'd realised we weren't testing for (though I guess 1.14 is close enough). We're discussing what to do about the 1.9 cluster already, perhaps a '1.9-support' tag that we can keep referencing, frozen unless there is something really critical to backport, would be a solution that lets us move forward and drop it.

**Comment by oyvindio** [comment]
If noone else uses 1.14, I maybe that could be replaced with 1.15 in the test suite.

> perhaps a '1.9-support' tag that we can keep referencing, frozen unless there is something really critical to backport, would be a solution that lets us move forward and drop it.

Do you mean a release tag to use with skipper (like "stable" and "latest") or a git tag? (or both?) Either way, it sounds like that could work.

**Comment by gregjones** [comment]
After looking more, we will use the skipper options to provide a hardcoded release-metadata that can point at an existing docker-tag, so I don't think there'll need to be other changes. So I think removing 1.9 and switching 1.14->1.15 is good 👍

**Comment by j18e** [comment]
We're looking at removing 1.9 as well as 1.12 and 1.14, then adding 1.15, 1.20 and 1.21. We'd really like feedback from anyone who's using other versions. Check out the PR here https://github.com/fiaas/fiaas-deploy-daemon/pull/161/files

**Comment by xavileon** [comment]
We (Adevinta) are still running 1.9 and 1.14 clusters. However, we understand we can't hold off this change given the long-term unsupported status for those versions, so we're happy to see this moving forward. We'll freeze the fiaas version on 1.9 and 1.14 clusters and enjoy the new versions in newer clusters.

We would like (if possible) to have some announcement in advance (message in slack channel is fine) before releasing stable so we know when those versions will move to officially unsupported and plan accordingly the freeze.

**Comment by oyvindio** [comment]
Fixed in #161
