### ISSUE TITLE
"Extensions" for fiaas applications

### ISSUE THREAD

**Issue by gregjones** [fiaas/fiaas-deploy-daemon#154]
We're receiving a number of requests from users who want fiaas to work in different ways for their use-cases, most recently (and most vocally) for some kind of "sidecar support" for their apps. We haven't been able to come up with a version of this feature that meets what seems to be a very disparate set of requirements that doesn't expose the full Deployment object as an API, so we've been looking at other ways to let us, and our users, experiment somehow with this feature, and others, perhaps to arrive at something that could be incorporated into the core project, or perhaps it can stay as an 'extension', living alongside the core.

So we've come up with a proposal for allowing the behaviour of fiaas, specifically the creation of the k8s objects, to be pluggable: between fiaas creating the object based on its internal logic and the Application configuration, and it being saved to the k8s API, we'd like to make an HTTP request to an external service, passing it the object that's about to be created along with the Application configuration.

The request would be to ${extensionServiceUrl}/fiaas/deploy/${Kind} (e.g. /fiaas/deploy/Ingress), and the body would contain serialized versions of the particular k8s object (e.g. the Ingress) and the AppSpec. 

The service will be able to make some modifications to that object before returning it, and the modified version is what fiaas will save to k8s. We imagine that the 'extensions' part of the current spec, perhaps necessitating the 'reservation' of some key there, would be where the logic for the modification comes from - it would then be up to the fiaas-admins for a cluster to explain/document this extra functionality for their users.

The changes to fiaas will be the introduction of a URL for this 'extension service', which will be optional, along with a new component that, given that base-URL, will be able to make HTTP requests. This component will then be called for each of the objects created (Deployment, Ingress, Service, HPA), and it will respond with the (potentially) modified object.

To allow for an implementation of the extension service to care only about a specific type, and allow some future extensibility, the service returning 404 will be ignored/skipped. Other errors will be logged and trigger failure, similar to validation problems inside fiaas, for example.

This first iteration should allow us to do some of the experimentation we'd like to do. If it seems useful enough, then being able to authenticate with the extension-service using a shared token (equivalent to how it's done for the usage-reporting) would be a likely short-term 2nd step. And adding extra hooks, perhaps before and after the full deploy-process, to allow dynamically modifying the Application config, or to cause some extra objects to be created, could be interesting too, though we don't have concrete use-cases for those right now.

We'll be opening PRs before too long, which can be used to discuss specifics of, for example, the API-contract between fiaas and the extension-service that we're still not 100% clear on, but I'm opening the issue now to see if there's any feedback on the idea itself.

**Comment by gregjones** [comment]
Yeah, we had considered the mutating webhook option, and it makes sense in a lot of ways, but (probably you remember) the team here managing fiaas isn't the same as the one that manages the clusters, which means it's currently not an option for us 😢

**Comment by j18e** [comment]
can this be closed then?

**Comment by xavileon** [comment]
Indeed, thanks for help grooming it.
