### ISSUE TITLE
The `secrets` field of serviceaccount resources is unset when updated by fiaas-deploy-daemon

### ISSUE THREAD

**Issue by oyvindio** [fiaas/fiaas-deploy-daemon#172]
When the service-account-per-app feature is enabled, fiaas-deploy-daemon seems to remove the secret field of managed serviceaccount resources when updating the resource on (re)deploy. This field is managed by the Kubernetes control plane, so the field being unset results in the control plane creating a new service account secret each time an application is deployed, leading to an unnecessary amount of service account secrets in the cluster.

**Comment by tg90nor** [comment]
For posterity: The issue with `get_or_create` is it overwrites field values from the apiserver with whatever would be set if you created a new resource. So if you don't specify a value for a field, it ends up with the default value.

**Comment by oyvindio** [comment]
This was fixed by #173
