### ISSUE TITLE
CrdWatcher change of behaviour

### ISSUE THREAD

**Issue by herodes1991** [fiaas/fiaas-deploy-daemon#174]
When the fiaas-deploy-daemon starts running, it is always updating the crd, even if is not needed.

Before it attempted first to watch out for the events in the namespace, and then, if it received a NotFound, it created the CRD. Now it is always updating the crd event before starting watching, firing some errors in our current system.

**Comment by oyvindio** [comment]
The behavior of updating the CRD every time fiaas-deploy-daemon starts was introduced in https://github.com/fiaas/fiaas-deploy-daemon/pull/169, to make it possible to upgrade to the v1 CRD API in a cluster where the application and applicationstatus already exists, by enabling the `use-apiextensionsv1-crd` config flag, and also make it possible downgrade to the v1beta1 CRD API by disabling the same flag later if necessary. With the previous behavior, this would be difficult to do without updating the application and applicationstatus CRDs manually. 
What kind of errors do you see as a result of this?

**Comment by herodes1991** [comment]
In our system, the team here managing fiaas isn't the same as the one that manages the clusters, meaning that fiaas-deploy-daemon has some reducen permissions on the cluster. 

Also, this change worries us a little bit because if the crd got updated with something that is not compatible with some K8s version, we would start having problems in some of our clusters, having to freeze the fiaas-deploy-daemon in those clusters

**Comment by herodes1991** [comment]
Also, I am seeing that Skipper is also in charge of creating/updating the CRD. 
Could this becomes a problem if skipper overwrites the CRD while fiaas-deploy-daemon is running?

**Comment by herodes1991** [comment]
I got it. 
As a summary: 

> this change is intended for two reasons: 
> 1. We want to rid of skipper eventually.
> 2. This is the easier way to support v1beta1 and v1 at the same time

Is this right?

**Comment by oyvindio** [comment]
> 1. We want to rid of skipper eventually.

Yes we do want to get rid of skipper eventually (as I gather this was the general consensus in #163)

> 2. This is the easier way to support v1beta1 and v1 at the same time

Yes, at least it was the best solution we could come up with. 
The reasoning is that CRDs are backed by the same resource at the storage level when accessed via the v1beta1 and v1 APIs, but v1 CRD require some changes in the structure (e.g. preserveUnknown fields must be false, schema is required). If the previous behavior of only creating the CRDs if they did not exist in was kept in fiaas-deploy-daemon, and only the API endpoint was changed from v1beta1 to v1, the CRD would not be updated to the new format after enabling `use-apiextensionsv1-crd` in fiaas-deploy-daemon, since fiaas-deploy-daemon would see that the CRDs already existed and then continue. The CRDs would have to be changed to the updated format elsewhere or manually, which could be prone to error.

**Comment by oyvindio** [comment]
> If enabling `use-apiextensionsv1-crd`, it is important to enable the flag in both skipper and fiaas-deploy-daemon at the same time to ensure both components agree about the CRDs structure. If not, then there would be a problem of each component overwriting the other's changes.

Another thing I forgot in my previous comment; I suppose it is also important to enable `use-apiextensionsv1-crd` at the same time in all fiaas-deploy-daemon instances in a cluster if running multiple instances in different namespaces too, since the CRDs are cluster level.

**Comment by herodes1991** [comment]
As in our architecture not all the accountservice has the possibility to create/update crds, we are thinking to add a new configuration flag to deactivate the crd creation.  By default, this flag will not be active and all the daemons will work as today. They will create/update the crds on start and then will return to watch.

With this approach everyone using multiple fiaas-deploy-daemons per cluster can "simulate" a kind of master/slave architecture, having only one daemon that updates the CRD and the other will go directly to watch.

WDYT @oyvindio? This will be a good approach to implement because will not modify the default behaviour and, in case or not have permissions, the daemon will be able to run without problems

**Comment by oyvindio** [comment]
> With this approach everyone using multiple fiaas-deploy-daemons per cluster can "simulate" a kind of master/slave architecture, having only one daemon that updates the CRD and the other will go directly to watch.

I think it sounds like a reasonable approach. It is only necessary for *one* fiaas-deploy-daemon instance to manage the CRDs, and disabling the CRD syncer can make it possible to have a little stricter rbac privileges for fiaas-deploy-daemon in namespaces where it doesn't need access to modify CRDs.

**Comment by herodes1991** [comment]
I will close the issue :) thanks for the help oyvindio!
