### ISSUE TITLE
Fiaas-deploy-daemon creating Role Bindings in addition to Service Account

### ISSUE THREAD

**Issue by herodes1991** [fiaas/fiaas-deploy-daemon#208]
We want to improve fiaas-deploy-daemon to create a role-binding in addition to service-account.

We are thinking of adding two configuration flags:
- To enable the creation of the role binding (i.e: --enable-role-binding-creation, by default will be false)
- The list of roles that should be bound for the role binding (i.e: `--list-of-cluster-roles=["A", "B"]` or `--list-of-roles=["A", "B"]`)

I created this issue to start discussing that. I would like to know your opinion 😄

**Comment by oyvindio** [comment]
This feature as it is described sounds reasonable enough to me, assuming the actual roles or clusterroles will be managed elsewhere.
