### ISSUE TITLE
Allow users to disable ingress

### ISSUE THREAD

**Issue by danmx** [fiaas/fiaas-deploy-daemon#22]
It's impossible to disable ingress for particular deployments.

One use case would be when multiple services are deployed using FIAAS and only one has to be exposed (have ingress).

**Comment by danmx** [comment]
fixed using:
```
ingress:
  host: null
```

**Comment by mortenlj** [comment]
Good that you have found a solution. This use case might also fall under the broader perspective of #8, which we have yet to find a good solution for.
