### ISSUE TITLE
How to share an API secret key amongst multiple applications?

### ISSUE THREAD

**Issue by leftieFriele** [fiaas/fiaas-deploy-daemon#236]
We have a use case where we have an API, the [Experience API](https://github.schibsted.io/nmp-web/experience-service), which is to be used by multiple NMP applications (meaning all Podium Layout applications which I think is like 60-70 at least). All applications need to authenticate with the API using a secret key of sorts.

Currently a few applications have done this by duplicating this secret and using `secrets_in_environment: true` in their `fiaas.yml`. However doing this for such a large number doesn't sound ideal and buts a big burden on the org for something small like this.

It would be nice for applications to say:  "I want secret XXX_YYYY from the shared vault" or something like that 🤷 

I am not an expert on FIAAS or infrastructure on this level, so I can't "order" anything 😄 but I'd be happy to help any way I can to figure out how to solve my issue.

There is [a conversation on Slack](https://sch-chat.slack.com/archives/C04F7G2N71V/p1709559552514859) with additional context.

**Comment by perj** [comment]
Hi. We've determined that if we make a solution for this, it will be made outside of fiaas-deploy-daemon. As such, I'll close this, I wrote a comment in the Slack thread.
