### ISSUE TITLE
Transition to apiextensions.k8s.io/v1 CustomResourceDefinition

### ISSUE THREAD

**Issue by oyvindio** [fiaas/fiaas-deploy-daemon#38]
The CustomResourceDefinition resource is out of beta in Kubernetes 1.16. apiextensions.k8s.io/v1beta1 CustomResourceDefinition, which FIAAS currently uses, will be removed in Kubernetes v1.22.

There are some changes that are necessary to transition FIAAS from using  to apiextensions.k8s.io/v1 CustomResourceDefinition; we need to determine exactly what these are, and how to implement the changes in FIAAS.

**Comment by oyvindio** [comment]
More details on the changes in apiextensions.k8s.io/v1 CustomResourceDefinition here: https://github.com/kubernetes/kubernetes/blob/b574074981a8fd0bdfb35090560b2d433b975e8d/CHANGELOG-1.16.md#api-changes

**Comment by oyvindio** [comment]
In apiextensions.k8s.io/v1 CustomResourceDefinition (CRD), a schema for the resource is required. Resources are validated against this schema on creation and update. The schema is expressed as OpenAPI v3 schema with some [additional rules](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema). In the v1beta1 CRD api, schemas are optional, and schema is not currently defined for `Application` or `ApplicationStatus` CRDs. As I understand it, CRD schema rules 1 and 3 imply that fields/nodes in the schema can have only one type, with two exceptions; 
- nodes can have `x-kubernetes-int-or-string: true`, which lets the node be either int or string.
- nodes can have `x-kubernetes-preserve-unknown-fields: true` which means the node can essentially be anything (with no validation).

It seems relatively straightforward to implement a schema for `ApplicationStatus` under these rules, since the resource only has two simple fields; `.result` and `.logs`. 

`Application` is a bit more complicated, mainly because of the `.spec.config` field which holds a full fiaas manifest (fiaas.yml) in either v2 or v3 format. Based on my understanding of the schema rules, it is not possible to specify a complete (i.e. without using `x-kubernetes-preserve-unknown-fields: true`) schema for this sub-tree of the resource, because of two reasons:
1) sub-fields of `.spec.config` have different types in v2 and v3 of the fiaas manifest format.
2) even if only v3 of the format was supported, the `extensions.tls` field can be both boolean (previous, currently undocumented format) and a object (current format). 

Based on this I see three approaches to implementing schema in the Application resource:
1) Remove support for fiaas manifest v2 and for setting `extensions.tls` to a boolean in v3, then specify a full schema for the `.spec.config` field.
    - Some application's configuration may have to change (update to v3, switch format for `extensions.tls`).
    - The full fiaas manifest can be validated before creation/update.
2) set `.spec` as `x-kubernetes-preserve-unknown-fields: true`
    - No application config should have to change.
    - No validation at all (same as current behavior).
3) set `.spec.config` as`x-kubernetes-preserve-unknown-fields: true`
    - No application config should have to change.
    - Fields other than .spec.config are validated before creation/update.

With the primary goal of having fiaas-deploy-daemon compatible with Kubernetes 1.22+, I think  approach 3 or 2 are the most reasonable in the short term, since it lets operators support the latest Kubernetes version without having to change application configuration at the same time. I think approach 3 has a slight benefit over approach 2 in that at least some fields are validated.
After Kubernetes 1.22 compatibility is in place, I think it would be a good idea to gradually work towards a complete schema for the `.spec.config` field in the `Application` resource  (as in approach 1). This could make it easier to build better developer UX for issues caused by invalid application configuration.

**Comment by tg90nor** [comment]
Fixed by #169
