### ISSUE TITLE
Default local/private endpoints

### ISSUE THREAD

**Issue by birgirst** [fiaas/fiaas-deploy-daemon#4]
Some HTTP endpoints exposed by applications deployed by FIAAS should generally not be available from the internet/outside the Kubernetes cluster. Typically this will be prometheus metrics endpoints, health endpoints and so on. Currently the defaults for these endpoints provided by FIAAS are grouped under `/_/`. This means that one way to solve this could be to employ the default that `/_/*` should be considered private by the ingress controller.

**Comment by mortenlj** [comment]
We should probably just document this expectation, but it should also probably integrate in some way with #8.
