### ISSUE TITLE
Transition from extensions/v1beta1 Ingress to networking.k8s.io/v1 Ingress

### ISSUE THREAD

**Issue by oyvindio** [fiaas/fiaas-deploy-daemon#40]
FIAAS currently uses extensions/v1beta1 Ingress. This API will be disabled in Kubernetes 1.20. networking.k8s.io/v1beta1 Ingress which is supposed to replace this API is available in Kubernetes 1.14 and later.

**Comment by oyvindio** [comment]
networking.k8s.io/v1 Ingress is GA in Kubernetes 1.19, and according to the [changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#api-change-4) it looks like the plan is to remove extensions/v1beta Ingress in Kubernetes 1.22 (or later?).

**Comment by tg90nor** [comment]
Fixed by #165
