### ISSUE TITLE
Create a Changelog when selecting a new stable version

### ISSUE THREAD

**Issue by mortenlj** [fiaas/fiaas-deploy-daemon#41]
When we mark a new version as stable, we should generate a Changelog (commits to master is probably good enough, similar to the one generated by [publish](https://github.com/fiaas/publish)) between this version and the previous stable.

This changelog should probably be made visible in Skipper, but the first iteration could be to just add it as a file next to the metadata json-file.

**Comment by oyvindio** [comment]
With the changes in #180, a changelog based on the pull requests merged since the previous release is generated and attached to the release in Github. There is also a link to the full diff between the previous and current release.
