### ISSUE TITLE
Wrong deployment status for 1 replica and singleton=false

### ISSUE THREAD

**Issue by adriengentil** [fiaas/fiaas-deploy-daemon#44]
Given a FIAAS application with this configuration:
```
...
replicas:
  singleton: false
  minimum: 1
  maximum: 1
...
```
Running successfully in the cluster:
```
$ kubectl get deployment
NAME      READY   UP-TO-DATE   AVAILABLE   AGE
example   1/1     1            1           4m30s
$ kubectl get pods
NAME                       READY   STATUS    RESTARTS   AGE
example-68b794f65f-tnqfv   1/1     Running   0          4m30s
$ kubectl get application-statuses -l "app=example" -oyaml
  result: SUCCESS
```

Now, I release a new version of my application but the new replica fails to start:
```
$ kubectl get deployment
NAME      READY   UP-TO-DATE   AVAILABLE   AGE
example   1/1     1            1           11m
$ kubectl get pods
NAME                       READY   STATUS             RESTARTS   AGE
example-68b794f65f-tnqfv   1/1     Running            0          11m
example-fcb8db6b9-9t255    0/1     CrashLoopBackOff   4          2m45s
$ kubectl get application-statuses -l "app=example" -oyaml
  result: SUCCESS
```
I would expect the fiaas deployment daemon to flag the deployment as a failure instead of a success.

**Comment by oyvindio** [comment]
If one of the pods fails to start and crashloops during a deployment, the status result should not be `SUCCESS`. There seem to be a few details missing in the description here though;
Are you sure that you are looking at the result from the correct ApplicationStatus resource? To verify, read the `fiaas/deployment_id` label on the Application resource after the failing deploy with `kubectl get application example -o yaml`, and use it to find the correct ApplicationStatus by using a label selector: `kubectl get appstatus -l fiaas/deployment_id=$deployment_id`.

**Comment by adriengentil** [comment]
Yes, I looked to the correct ApplicationStatus. Here are the Application objects that I used:
https://gist.github.com/adriengentil/5aeb320918896de6b8ae34fc9d8177f3

If you apply `example-success.yaml` and `example-fail.yaml` in that order, then you should be able to reproduce the issue.

My guess on this issue:
FIAAS monitors the deployment object and its fields `up-to-date` and `available` to compute the status of the deployment: https://github.com/fiaas/fiaas-deploy-daemon/blob/master/fiaas_deploy_daemon/deployer/kubernetes/ready_check.py#L61.

But the field `available` counts all the replicas available, not only the ones among `up-to-date` (this is what we see in my first post).

As a consequence, when performing a rollingUpdate for 1 replica, the checks in FIAAS are always successful (1 pod up-to-date and 1 pod available, the former one).

**Comment by mortenlj** [comment]
@adriengentil is quite right, and this has long been a known (to me atleast) problem with the way we handle this. It was made this way because at the time we made it, there were no other information available to determine the status. We should probably change to use the built-in deployment rollout status that was introduced some time ago (`DeploymentCondition`).

**Comment by adriengentil** [comment]
It seems the `DeploymentCondition` is not the solution:
```
...
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2019-11-14T14:11:01Z"
      lastUpdateTime: "2019-11-14T14:11:01Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 7
    readyReplicas: 1
    replicas: 2
    unavailableReplicas: 1
    updatedReplicas: 1
...
```
Or maybe you were thinking about another stuff?

In the meantime, I did some research and found that Kubernetes defines a complete deployment with this [condition](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/util/deployment_util.go#L736).
I think this is what we are looking for in our case. I'm currently testing this condition locally in FIAAS and it fixes this issue. If don't foresee any problems with it, I will open a PR.
