### ISSUE TITLE
Update integration tests to test against updated k8s versions

### ISSUE THREAD

**Issue by birgirst** [fiaas/fiaas-deploy-daemon#5]
Shift the kubernetes versions in e2e tests to updated versions (min 1.9.x)

**Comment by srvaroa** [comment]
We're already providing 1.14 clusters so this one is quite desirable.

**Comment by mortenlj** [comment]
Shifting the versions in the e2e test is a one-line change, but when we get to the point where we don't support any version of Kubernetes that uses Third Party Resources, we should also remove the code for those. That would reduce the codebase significantly, and also simplify some parts of it.

**Comment by mortenlj** [comment]
Fixed in #26
