### ISSUE TITLE
Upgrade to python 3

### ISSUE THREAD

**Issue by birgirst** [fiaas/fiaas-deploy-daemon#6]
Work is underway to remove integration with Kafka that uses python 2.7 libraries.
Once that is complete fiaas-deploy-daemon can be upgraded to python 3.

**Comment by sa-mao** [comment]
Is this a stalling issue? It would be nice if we upgrade to python 3.

**Comment by mortenlj** [comment]
@oyvindio : Correct me if I'm wrong, but I think everything is ready for an upgrade to Python 3 now?

**Comment by oyvindio** [comment]
> @oyvindio : Correct me if I'm wrong, but I think everything is ready for an upgrade to Python 3 now?

Yes there is nothing blocking a migration to Python 3 that I'm aware of now, and it is clearly something that should be done. I started looked into it at one point, but haven't been able to spend much time on getting it working yet
