### ISSUE TITLE
Clean up environment variables passed to apps

### ISSUE THREAD

**Issue by mortenlj** [fiaas/fiaas-deploy-daemon#70]
When fiaas deploys an application, a number of environment variables are set, from a number of sources. Some of these have been "marked" as deprecated (by virtue of a comment in the source code) for ages, some are somewhat weird FINN legacy stuff and some are useful but badly named.

I'd like to do a clean up, but it probably requires a detailed plan for how to go about it, so that users have time to update their applications. 

In addition to the ones FDD sets directly, we have the environment variables that comes from global config. Because we at some point thought it would be best to set a prefix to all environment variables supplied by fiaas, we added copies of all of them with the `FIAAS_` prefix with the intention to remove the non-prefixed ones later. We never followed through, and I think that's a good thing.

I'd like to clean this up, following these principles:
- Environment variables from global config are kept as is. It's up to the cluster operator to ensure that they are unique enough.
- Environment variables set by FDD for internal reasons, should have the `FIAAS_` prefix.
- Environment variables that are a legacy from FINN should be removed or replaced where needed (see table below)

This leads to me wanting to make these changes (this might also solve #12, since we remove the propagated variables completely):

| Name | Value | What to do with it |
|------|-------|--------------------|
| ARTIFACT_NAME | Name of application | Rename to FIAAS_APPLICATION_NAME. (for FINN, this requires some work, since ARTIFACT_NAME is use "everywhere" in common libraries) |
| CONSTRETTO_TAGS | Legacy FINN support | Remove (for FINN: move to global config) |
| FINN_ENV | Same as FIAAS_ENVIRONMENT, legacy from FINN. Considered deprecated for ages. | Remove |
| IMAGE | Name of deployed image. Could be useful for applications. | Rename to FIAAS_IMAGE |
| LOG_FORMAT | Logging format (plain/json). Propagated from FDDs own config. Legacy from FINN. | Remove (for FINN: move to global config) |
| LOG_STDOUT | Logging destination (true->stdout/false->file). Hardcoded to true. Legacy from FINN. | Remove (for FINN: move to global config) |
| VERSION | Version of deployed image (ie. tag of container). Might be useful, but we already have cases of name collision. | Rename to FIAAS_IMAGE_VERSION |
| | | |
| FIAAS_ENVIRONMENT | Propagated from FDDs config. Should describe environment. | Remove. If cluster operators needs it, they can put it in global config. |
| FIAAS_INFRASTRUCTURE |  Propagated from FDDs config. Should describe infrastructure of current cluster. Legacy from FINN and marked as deprecated. | Remove |
| | | |
| FIAAS_LIMITS_CPU | Comes from resource limits | Keep as is |
| FIAAS_LIMITS_MEMORY | Comes from resource limits | Keep as is |
| FIAAS_REQUESTS_CPU | Comes from resource requests | Keep as is |
| FIAAS_REQUESTS_MEMORY | Comes from resource requests | Keep as is |
| FIAAS_NAMESPACE | Contains namespace app is in | The namespace is available as a file, but not everyone knows this, so having it as environment variable is useful. Keep as is. |
| FIAAS_POD_NAME | Contains name of pod | This values is available as hostname, but it's easier to just take from environment. Keep as is. |

**Comment by oyvindio** [comment]
Maybe the first step of removing most of these environment variables is to make it possible to override the values of the following with `global-env`?

- CONSTRETTO_TAGS
- FINN_ENV
- LOG_FORMAT
- LOG_STDOUT
- FIAAS_ENVIRONMENT
- FIAAS_INFRASTRUCTURE

**Comment by oyvindio** [comment]
I created a draft PR (#106) for the above suggestion. I'm interested to hear any input on this approach
