### ISSUE TITLE
Support separate service accounts per application

### ISSUE THREAD

**Issue by xavileon** [fiaas/fiaas-deploy-daemon#72]
FIAAS only supports using the default service account in Deployment objects to map the k8s API token inside the pod (if instructed to do so).

AWS EKS use service accounts to inject IAM Roles and provide fine-grained authorization to the AWS API, a similar functionality that `kiam` provides (using service accounts instead of annotations on pods).

To support this use case, FIAAS should allow binding different service accounts per application. This could work as follows:
- FDD will have a new setting (separateServiceAccountPerApplication) that will create a service account with the application name (if it doesn't exist), following the FIAAS naming convention.
- Deployment objects will bind this new service account in the Deployment object instead of the default account.

If the cluster operator wants to provide IAM roles for a given application, the operator may configure the app specific service account accordingly following https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

Thoughts?

**Comment by oyvindio** [comment]
I think this sounds like a very useful feature. Only creating the service accounts and not roles with rules makes it very flexible too in terms of building your own authorization regime.

I also think that this can be used to improve the current RBAC setup that skipper creates. Currently, skipper creates a [fiaas-controller](https://github.com/fiaas/skipper/blob/master/helm/fiaas-skipper/templates/rbac.yaml#L24) role and binds it to [`system:serviceaccounts`](https://github.com/fiaas/skipper/blob/master/helm/fiaas-skipper/templates/rbac.yaml#L77) via a clusterrolebinding. This is setup is a fair bit more permissive than necessary. If fiaas-deploy-daemon created serviceaccounts for each application, I think this could be limited down to only bind the role to the fiaas-deploy-daemon (and skipper and possibly mast) serviceaccounts in each namespace.

**Comment by sa-mao** [comment]
I also this would make a very nice feature specially with AWS IRSA.

**Comment by stribb** [comment]
How close are we here?

Thanks :)

**Comment by oyvindio** [comment]
This feature was added in #159
